### ISSUE TITLE
import notes?

### ISSUE THREAD

**Issue by danwashburn** [AndyHitchman/DeliciousToGoogleBookmarks#2]
Everything worked great -- bookmarks and tags were imported -- but the notes/text associated with each bookmark on Delicious was not. Do you plan on adding this feature?

Regardless, thanks for building this tool.

**Comment by AndyHitchman** [comment]
I attempted to do this, but it looks like Google doesn't support it, or at least I can't work it out (there isn't really any documentation). Sorry.
